version: "3.9"

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vite_dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      # Добавьте ваши переменные, если нужно
      VITE_API_URL: "http://localhost:3000/api"
